require:
  - rubocop-rails
  - rubocop-minitest

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - config/**/*
    - bin/**/*
    - db/**/*
    - tmp/**/*
  DisplayCopNames: true
  DisplayStyleGuide: true
