Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - config/**/*
    - bin/**/*
    - db/**/*
    - tmp/**/*
  DisplayCopNames: true
  DisplayStyleGuide: true
